#############################################################
# APPLICATION NANME
#############################################################
spring.application.name=riesgo-psicosocial
#############################################################
# SERVER
#############################################################
server.port=8080
server.servlet.context-path=/api

#############################################################
# PORFILES
#############################################################
spring.profiles.active=dev

#############################################################
# JPA
#############################################################
spring.jpa.open-in-view=false

#############################################################
# JACKSON
#############################################################
spring.jackson.time-zone=America/Bogota
spring.jackson.serialization.write-dates-as-timestamps=false

#############################################################
# FLYWAY
#############################################################
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=false

#############################################################
# LOGGING
#############################################################
logging.config=classpath:logback-spring.xml

#############################################################
# SWAGGER
#############################################################
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#############################################################
# CONTROL-ARCHIVOS
#############################################################
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB